---
- hosts: all
  tasks:
  - name: make sure chronyd is installed
    yum:
     name: chrony
     state: latest
     update_cache: yes
    when: {{ ansible_distribution }} == 'RedHat' or {{ ansible_distribution }} == 'CentOs' and {{ ansible_distribution_version }} > 7
  - name: deploy chrony.conf template
    template:
     src: /some/full/path/chrony.conf.j2
     dest: /etc/chrony.conf
     owner: root
     group: root
     mode: 0644
     backup: yes
    when: {{ ansible_distribution }} == 'RedHat' or {{ ansible_distribution }} == 'CentOs' and {{ ansible_distribution_version }} > 7

  - name: Restart chronyd
    service:
      name: chronyd
      state: restarted
    when: {{ ansible_distribution }} == 'RedHat' or {{ ansible_distribution }} == 'CentOs' and {{ ansible_distribution_version }} > 7
