- hosts: all
  pre_tasks:
  - name: Gather the package facts
    ansible.builtin.package_facts:
        manager: auto

  roles:
    - role: diodonfrost.logrotate
      vars:
        logrotate_entries:
          - name: nginx
            paths:
              - /var/log/nginx/*.log
            options:
              - weekly
              - compress
          - name: rsyslog
            paths:
              - /var/log/kern.log
              - /var/log/message
              - /var/log/debug
            options:
              - weekly
              - rotate 4
              - compress
              - size 100M
      when: "'nginx' in ansible_facts.packages"

