---
- hosts: {{ new_vmname }}
  vars:

  tasks:
    - name: Crear config para ipv6 en sysctl.d
      lineinfile:
         path: /etc/systctl.d/ipv6.conf
         line: 
           - "# First, disable for all interfaces"
           - "net.ipv6.conf.all.disable_ipv6 = 1" 
         insertbefore: EOF

    - name: Por cada interfaz:
      lineinfile:
        path: /etc/sysctl.d/ipv6.conf
        line: "net.ipv6.conf.item.disable_ipv6 = 1"
      inserbefore: EOF
      with_items: ansible_interfaces
        
    - name: "Apply config"
      command: sysctl -p /etc/sysctl.d/ipv6.conf
      register: sysctl -p

    - name: "Regenerate Initial RAM disk"
      command: dracut -f -v
      register: dracut
      when: ansible_facts['os_family'] == "RedHat"

    - name: "Fix hosts table"
      replace:
        dest: /etc/hosts
        regexp: "^[[:space:]]*::"
        replace: ""#::"
        backup: yes
 

