---
- name: Viabilidad de DRP en Azure
  hosts: all

  tasks:

  - name: Copiar Script
    copy: src=drponazure.sh dest=/tmp mode=0555

  - name: Execute
    command: sh /tmp/drponazure.sh
    ignore_errors: yes
    register drponazure
    failed_when: drponazure.rc == 0
