---
- name: Viabilidad de DRP en Azure
  hosts: all
  ignore_errors: yes
  meta: clear_host_errors
  failed_when: diff_cmd.rc == 0
  tasks:

  - name: Copiar Script
    copy: src=drponazure.sh dest=/tmp mode=0555

  - name: Execute
    command: sh /tmp/drponazure.sh
