---
- hosts: all
#  gather_facts: yes
#  become: false
  tasks:
  - debug:
      msg:
      - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}{{ hostvars[inventory_hostname].ansible_distribution_major_version }}{{ hostvars[inventory_hostname].ansible_distribution_version }}"
      - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
      - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"

