---
- hosts: all
#  gather_facts: yes
#  become: false
  tasks:
  - debug:
      msg:
      - "VM Get-VM {{ inventory_hostname }} | New-TagAssignment -Tag {{ hostvars[inventory_hostname].ansible_distribution }}{{ hostvars[inventory_hostname].ansible_distribution_version }}"
