---
- hosts: all
  vars:
    package_names:
      - chrony
      - ntp
 
  tasks:
    - name: "Check if listed package is installed or not on Debian Linux family"
      command: dpkg-query -l "{{ item }}"
      loop: "{{ package_names }}"
      register: package_check
      when: ansible_facts['os_family'] == "Debian"

    - name: "Check if listed package is installed or not on Red Hat Linux family"
      command: rpm -q "{{ item }}"
      loop: "{{ package_names }}"
      register: package_check
      when: ansible_facts['os_family'] == "RedHat"

    - name: "Print execution results"
      debug:
        msg: "Package {{ item }} is installed"
      when: package_check is succeeded
  when:
    ansible_hostname == "AODCSRV01-DESA"
