---
- hosts: all
#  gather_facts: yes
#  become: false
  tasks:
  - debug:
      msg:
      - "VM {{ inventory_hostname }} {{ hostvars[inventory_hostname].ansible_distribution }}{{ hostvars[inventory_hostname].ansible_distribution_version }}"
