---
- hosts: all
  tasks:
    # Example removing a repository and cleaning up metadata cache
    - name: Remove repository (and clean up left-over metadata)
      yum_repository:
        name: codeready-builder-for-rhel-8-x86_64-eus-debug-rpms
        state: absent
      notify: yum-clean-metadata
       
    - name: Remove repository (and clean up left-over metadata)
      yum_repository:
        state: absent
        name:ansible-2-for-rhel-8-x86_64-debug-rpms
        name:ansible-2-for-rhel-8-x86_64-rpms
        name:ansible-2-for-rhel-8-x86_64-source-rpms
        name:ansible-2.8-for-rhel-8-x86_64-debug-rpms
        name:ansible-2.8-for-rhel-8-x86_64-rpms
        name:ansible-2.8-for-rhel-8-x86_64-source-rpms
        name:ansible-2.9-for-rhel-8-x86_64-debug-rpms
        name:ansible-2.9-for-rhel-8-x86_64-rpms
        name:ansible-2.9-for-rhel-8-x86_64-source-rpms
        name:cnv-2.0-for-rhel-8-x86_64-debug-rpms
        name:cnv-2.0-for-rhel-8-x86_64-rpms
        name:cnv-2.0-for-rhel-8-x86_64-source-rpms
        name:cnv-2.1-for-rhel-8-x86_64-debug-rpms
        name:cnv-2.1-for-rhel-8-x86_64-rpms
        name:cnv-2.1-for-rhel-8-x86_64-source-rpms
        name:cnv-2.2-for-rhel-8-x86_64-debug-rpms
        name:cnv-2.2-for-rhel-8-x86_64-rpms
        name:cnv-2.2-for-rhel-8-x86_64-source-rpms
        name:cnv-2.3-for-rhel-8-x86_64-debug-rpms
        name:cnv-2.3-for-rhel-8-x86_64-rpms
        name:cnv-2.3-for-rhel-8-x86_64-source-rpms
        name:cnv-2.4-for-rhel-8-x86_64-debug-rpms
        name:cnv-2.4-for-rhel-8-x86_64-rpms
        name:cnv-2.4-for-rhel-8-x86_64-source-rpms
        name:cnv-2.5-for-rhel-8-x86_64-debug-rpms
        name:cnv-2.5-for-rhel-8-x86_64-rpms
        name:cnv-2.5-for-rhel-8-x86_64-source-rpms
        name:cnv-2.6-for-rhel-8-x86_64-debug-rpms
        name:cnv-2.6-for-rhel-8-x86_64-rpms
        name:cnv-2.6-for-rhel-8-x86_64-source-rpms
        name:cnv-2.7-for-rhel-8-x86_64-debug-rpms
        name:cnv-2.7-for-rhel-8-x86_64-rpms
        name:cnv-2.7-for-rhel-8-x86_64-source-rpms
        name:cnv-4.10-for-rhel-8-x86_64-debug-rpms
        name:cnv-4.10-for-rhel-8-x86_64-rpms
        name:cnv-4.10-for-rhel-8-x86_64-source-rpms
        name:cnv-4.8-for-rhel-8-x86_64-debug-rpms
        name:cnv-4.8-for-rhel-8-x86_64-rpms
        name:cnv-4.8-for-rhel-8-x86_64-source-rpms
        name:cnv-4.9-for-rhel-8-x86_64-debug-rpms
        name:cnv-4.9-for-rhel-8-x86_64-rpms
        name:cnv-4.9-for-rhel-8-x86_64-source-rpms
        name:codeready-builder-for-rhel-8-x86_64-debug-rpms
        name:codeready-builder-for-rhel-8-x86_64-eus-debug-rpms
        name:codeready-builder-for-rhel-8-x86_64-eus-rpms
        name:codeready-builder-for-rhel-8-x86_64-eus-source-rpms
        name:codeready-builder-for-rhel-8-x86_64-rpms
        name:codeready-builder-for-rhel-8-x86_64-source-rpms
        name:devworkspace-1.0-for-rhel-8-x86_64-debug-rpms
        name:devworkspace-1.0-for-rhel-8-x86_64-rpms
        name:devworkspace-1.0-for-rhel-8-x86_64-source-rpms
        name:epel
        name:epel-debuginfo
        name:epel-modular
        name:epel-modular-debuginfo
        name:epel-modular-source
        name:epel-playground
        name:epel-playground-debuginfo
        name:epel-playground-source
        name:epel-source
        name:epel-testing
        name:epel-testing-debuginfo
        name:epel-testing-modular
        name:epel-testing-modular-debuginfo
        name:epel-testing-modular-source
        name:epel-testing-source
        name:fast-datapath-beta-for-rhel-8-x86_64-debug-rpms
        name:fast-datapath-beta-for-rhel-8-x86_64-rpms
        name:fast-datapath-beta-for-rhel-8-x86_64-source-rpms
        name:fast-datapath-for-rhel-8-x86_64-debug-rpms
        name:fast-datapath-for-rhel-8-x86_64-rpms
        name:fast-datapath-for-rhel-8-x86_64-source-rpms
        name:gitops-1.0-for-rhel-8-x86_64-debug-rpms
        name:gitops-1.0-for-rhel-8-x86_64-rpms
        name:gitops-1.0-for-rhel-8-x86_64-source-rpms
        name:gitops-1.1-for-rhel-8-x86_64-debug-rpms
        name:gitops-1.1-for-rhel-8-x86_64-rpms
        name:gitops-1.1-for-rhel-8-x86_64-source-rpms
        name:gitops-1.2-for-rhel-8-x86_64-debug-rpms
        name:gitops-1.2-for-rhel-8-x86_64-rpms
        name:gitops-1.2-for-rhel-8-x86_64-source-rpms
        name:jws-5-for-rhel-8-x86_64-debug-rpms
        name:jws-5-for-rhel-8-x86_64-rpms
        name:jws-5-for-rhel-8-x86_64-source-rpms
        name:jws-textonly-1-for-middleware-rpms
        name:ocp-tools-4.3-for-rhel-8-x86_64-debug-rpms
        name:ocp-tools-4.3-for-rhel-8-x86_64-rpms
        name:ocp-tools-4.3-for-rhel-8-x86_64-source-rpms
        name:ocp-tools-4.4-for-rhel-8-x86_64-debug-rpms
        name:ocp-tools-4.4-for-rhel-8-x86_64-rpms
        name:ocp-tools-4.4-for-rhel-8-x86_64-source-rpms
        name:ocp-tools-4.5-for-rhel-8-x86_64-debug-rpms
        name:ocp-tools-4.5-for-rhel-8-x86_64-rpms
        name:ocp-tools-4.5-for-rhel-8-x86_64-source-rpms
        name:ocp-tools-4.6-for-rhel-8-x86_64-debug-rpms
        name:ocp-tools-4.6-for-rhel-8-x86_64-rpms
        name:ocp-tools-4.6-for-rhel-8-x86_64-source-rpms
        name:ocp-tools-4.7-for-rhel-8-x86_64-debug-rpms
        name:ocp-tools-4.7-for-rhel-8-x86_64-rpms
        name:ocp-tools-4.7-for-rhel-8-x86_64-source-rpms
        name:ocp-tools-4.8-for-rhel-8-x86_64-debug-rpms
        name:ocp-tools-4.8-for-rhel-8-x86_64-rpms
        name:ocp-tools-4.8-for-rhel-8-x86_64-source-rpms
        name:openshift-serverless-1-for-rhel-8-x86_64-debug-rpms
        name:openshift-serverless-1-for-rhel-8-x86_64-rpms
        name:openshift-serverless-1-for-rhel-8-x86_64-source-rpms
        name:openstack-15-tools-for-rhel-8-x86_64-debug-rpms
        name:openstack-15-tools-for-rhel-8-x86_64-rpms
        name:openstack-15-tools-for-rhel-8-x86_64-source-rpms
        name:openstack-16-tools-for-rhel-8-x86_64-debug-rpms
        name:openstack-16-tools-for-rhel-8-x86_64-rpms
        name:openstack-16-tools-for-rhel-8-x86_64-source-rpms
        name:ossm-0-for-rhel-8-x86_64-debug-rpms
        name:ossm-0-for-rhel-8-x86_64-rpms
        name:ossm-0-for-rhel-8-x86_64-source-rpms
        name:ossm-1.0-for-rhel-8-x86_64-debug-rpms
        name:ossm-1.0-for-rhel-8-x86_64-rpms
        name:ossm-1.0-for-rhel-8-x86_64-source-rpms
        name:ossm-1.1-for-rhel-8-x86_64-debug-rpms
        name:ossm-1.1-for-rhel-8-x86_64-rpms
        name:ossm-1.1-for-rhel-8-x86_64-source-rpms
        name:ossm-2.0-for-rhel-8-x86_64-debug-rpms
        name:ossm-2.0-for-rhel-8-x86_64-rpms
        name:ossm-2.0-for-rhel-8-x86_64-source-rpms
        name:ossm-2.1-for-rhel-8-x86_64-debug-rpms
        name:ossm-2.1-for-rhel-8-x86_64-rpms
        name:ossm-2.1-for-rhel-8-x86_64-source-rpms
        name:pipelines-1.0-for-rhel-8-x86_64-debug-rpms
        name:pipelines-1.0-for-rhel-8-x86_64-rpms
        name:pipelines-1.0-for-rhel-8-x86_64-source-rpms
        name:pipelines-1.1-for-rhel-8-x86_64-debug-rpms
        name:pipelines-1.1-for-rhel-8-x86_64-rpms
        name:pipelines-1.1-for-rhel-8-x86_64-source-rpms
        name:pipelines-1.2-for-rhel-8-x86_64-debug-rpms
        name:pipelines-1.2-for-rhel-8-x86_64-rpms
        name:pipelines-1.2-for-rhel-8-x86_64-source-rpms
        name:pipelines-1.3-for-rhel-8-x86_64-debug-rpms
        name:pipelines-1.3-for-rhel-8-x86_64-rpms
        name:pipelines-1.3-for-rhel-8-x86_64-source-rpms
        name:pipelines-1.4-for-rhel-8-x86_64-debug-rpms
        name:pipelines-1.4-for-rhel-8-x86_64-rpms
        name:pipelines-1.4-for-rhel-8-x86_64-source-rpms
        name:pipelines-1.5-for-rhel-8-x86_64-debug-rpms
        name:pipelines-1.5-for-rhel-8-x86_64-rpms
        name:pipelines-1.5-for-rhel-8-x86_64-source-rpms
        name:quarkus-1-for-rhel-8-x86_64-debug-rpms
        name:quarkus-1-for-rhel-8-x86_64-rpms
        name:quarkus-1-for-rhel-8-x86_64-source-rpms
        name:quarkus-2.2-for-rhel-8-x86_64-debug-rpms
        name:quarkus-2.2-for-rhel-8-x86_64-rpms
        name:quarkus-2.2-for-rhel-8-x86_64-source-rpms
        name:quarkus-textonly-1-for-middleware-rpms
        name:rh-gluster-3-client-for-rhel-8-x86_64-debug-rpms
        name:rh-gluster-3-client-for-rhel-8-x86_64-rpms
        name:rh-gluster-3-client-for-rhel-8-x86_64-source-rpms
        name:rh-sso-7.3-for-rhel-8-x86_64-debug-rpms
        name:rh-sso-7.3-for-rhel-8-x86_64-rpms
        name:rh-sso-7.3-for-rhel-8-x86_64-source-rpms
        name:rh-sso-7.4-for-rhel-8-x86_64-debug-rpms
        name:rh-sso-7.4-for-rhel-8-x86_64-rpms
        name:rh-sso-7.4-for-rhel-8-x86_64-source-rpms
        name:rh-sso-textonly-1-for-middleware-rpms
        name:rhceph-4-tools-for-rhel-8-x86_64-debug-rpms
        name:rhceph-4-tools-for-rhel-8-x86_64-rpms
        name:rhceph-4-tools-for-rhel-8-x86_64-source-rpms
        name:rhceph-5-tools-for-rhel-8-x86_64-debug-rpms
        name:rhceph-5-tools-for-rhel-8-x86_64-rpms
        name:rhceph-5-tools-for-rhel-8-x86_64-source-rpms
        name:rhel-8-for-x86_64-appstream-debug-rpms
        name:rhel-8-for-x86_64-appstream-eus-debug-rpms
        name:rhel-8-for-x86_64-appstream-eus-rpms
        name:rhel-8-for-x86_64-appstream-eus-source-rpms
        name:rhel-8-for-x86_64-appstream-rpms
        name:rhel-8-for-x86_64-appstream-source-rpms
        name:rhel-8-for-x86_64-baseos-debug-rpms
        name:rhel-8-for-x86_64-baseos-eus-debug-rpms
        name:rhel-8-for-x86_64-baseos-eus-rpms
        name:rhel-8-for-x86_64-baseos-eus-source-rpms
        name:rhel-8-for-x86_64-baseos-rpms
        name:rhel-8-for-x86_64-baseos-source-rpms
        name:rhel-8-for-x86_64-supplementary-debug-rpms
        name:rhel-8-for-x86_64-supplementary-eus-debug-rpms
        name:rhel-8-for-x86_64-supplementary-eus-rpms
        name:rhel-8-for-x86_64-supplementary-eus-source-rpms
        name:rhel-8-for-x86_64-supplementary-rpms
        name:rhel-8-for-x86_64-supplementary-source-rpms
        name:rhocp-4.1-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.1-for-rhel-8-x86_64-rpms
        name:rhocp-4.1-for-rhel-8-x86_64-source-rpms
        name:rhocp-4.2-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.2-for-rhel-8-x86_64-rpms
        name:rhocp-4.2-for-rhel-8-x86_64-source-rpms
        name:rhocp-4.3-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.3-for-rhel-8-x86_64-rpms
        name:rhocp-4.3-for-rhel-8-x86_64-source-rpms
        name:rhocp-4.4-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.4-for-rhel-8-x86_64-rpms
        name:rhocp-4.4-for-rhel-8-x86_64-source-rpms
        name:rhocp-4.5-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.5-for-rhel-8-x86_64-rpms
        name:rhocp-4.5-for-rhel-8-x86_64-source-rpms
        name:rhocp-4.6-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.6-for-rhel-8-x86_64-rpms
        name:rhocp-4.6-for-rhel-8-x86_64-source-rpms
        name:rhocp-4.7-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.7-for-rhel-8-x86_64-rpms
        name:rhocp-4.7-for-rhel-8-x86_64-source-rpms
        name:rhocp-4.8-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.8-for-rhel-8-x86_64-rpms
        name:rhocp-4.8-for-rhel-8-x86_64-source-rpms
        name:rhocp-4.9-for-rhel-8-x86_64-debug-rpms
        name:rhocp-4.9-for-rhel-8-x86_64-rpms
        name:rhocp-4.9-for-rhel-8-x86_64-source-rpms
        name:rhosj-1.17-for-rhel-8-x86_64-debug-rpms
        name:rhosj-1.17-for-rhel-8-x86_64-rpms
        name:rhosj-1.17-for-rhel-8-x86_64-source-rpms
        name:rhosj-1.20-for-rhel-8-x86_64-debug-rpms
        name:rhosj-1.20-for-rhel-8-x86_64-rpms
        name:rhosj-1.20-for-rhel-8-x86_64-source-rpms
        name:rhosj-1.22-for-rhel-8-x86_64-debug-rpms
        name:rhosj-1.22-for-rhel-8-x86_64-rpms
        name:rhosj-1.22-for-rhel-8-x86_64-source-rpms
        name:rhosj-1.24-for-rhel-8-x86_64-debug-rpms
        name:rhosj-1.24-for-rhel-8-x86_64-rpms
        name:rhosj-1.24-for-rhel-8-x86_64-source-rpms
        name:rhosj-2.0-for-rhel-8-x86_64-debug-rpms
        name:rhosj-2.0-for-rhel-8-x86_64-rpms
        name:rhosj-2.0-for-rhel-8-x86_64-source-rpms
        name:rhv-4-tools-beta-for-rhel-8-x86_64-debug-rpms
        name:rhv-4-tools-beta-for-rhel-8-x86_64-rpms
        name:rhv-4-tools-beta-for-rhel-8-x86_64-source-rpms
        name:rhv-4-tools-for-rhel-8-x86_64-debug-rpms
        name:rhv-4-tools-for-rhel-8-x86_64-rpms
        name:rhv-4-tools-for-rhel-8-x86_64-source-rpms
        name:satellite-tools-6-beta-for-rhel-8-x86_64-debug-rpms
        name:satellite-tools-6-beta-for-rhel-8-x86_64-rpms
        name:satellite-tools-6-beta-for-rhel-8-x86_64-source-rpms
        name:satellite-tools-6.5-for-rhel-8-x86_64-debug-rpms
        name:satellite-tools-6.5-for-rhel-8-x86_64-eus-debug-rpms
        name:satellite-tools-6.5-for-rhel-8-x86_64-eus-rpms
        name:satellite-tools-6.5-for-rhel-8-x86_64-eus-source-rpms
        name:satellite-tools-6.5-for-rhel-8-x86_64-rpms
        name:satellite-tools-6.5-for-rhel-8-x86_64-source-rpms
        name:satellite-tools-6.6-for-rhel-8-x86_64-debug-rpms
        name:satellite-tools-6.6-for-rhel-8-x86_64-eus-debug-rpms
        name:satellite-tools-6.6-for-rhel-8-x86_64-eus-rpms
        name:satellite-tools-6.6-for-rhel-8-x86_64-eus-source-rpms
        name:satellite-tools-6.6-for-rhel-8-x86_64-rpms
        name:satellite-tools-6.6-for-rhel-8-x86_64-source-rpms
        name:satellite-tools-6.7-for-rhel-8-x86_64-debug-rpms
        name:satellite-tools-6.7-for-rhel-8-x86_64-eus-debug-rpms
        name:satellite-tools-6.7-for-rhel-8-x86_64-eus-rpms
        name:satellite-tools-6.7-for-rhel-8-x86_64-eus-source-rpms
        name:satellite-tools-6.7-for-rhel-8-x86_64-rpms
        name:satellite-tools-6.7-for-rhel-8-x86_64-source-rpms
        name:satellite-tools-6.8-for-rhel-8-x86_64-debug-rpms
        name:satellite-tools-6.8-for-rhel-8-x86_64-eus-debug-rpms
        name:satellite-tools-6.8-for-rhel-8-x86_64-eus-rpms
        name:satellite-tools-6.8-for-rhel-8-x86_64-eus-source-rpms
        name:satellite-tools-6.8-for-rhel-8-x86_64-rpms
        name:satellite-tools-6.8-for-rhel-8-x86_64-source-rpms
        name:satellite-tools-6.9-for-rhel-8-x86_64-debug-rpms
        name:satellite-tools-6.9-for-rhel-8-x86_64-eus-debug-rpms
        name:satellite-tools-6.9-for-rhel-8-x86_64-eus-rpms
        name:satellite-tools-6.9-for-rhel-8-x86_64-eus-source-rpms
        name:satellite-tools-6.9-for-rhel-8-x86_64-rpms
        name:satellite-tools-6.9-for-rhel-8-x86_64-source-rpms
      notify: yum-clean-metadata
       
    - name: Register RHEL
      community.general.redhat_subscription:
        state: present
        username: ddf4-90a6-de5f-b290
        password: rhel4ndr34n1#
        pool_ids: 8a85f9997527b04201752908e64d6a5d
        
    - name: Add repository
      yum_repository:
        name: rhel-8-for-x86_64-baseos-rpms
        description: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
        baseurl: https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/baseos/os
        enabled: 1
        gpgcheck: 1
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        sslverify: 1
        sslcacert: /etc/rhsm/ca/redhat-uep.pem
        sslclientkey: /etc/pki/entitlement/8315695045436431682-key.pem
        sslclientcert: /etc/pki/entitlement/8315695045436431682.pem
        metadata_expire: 86400
        enabled_metadata: 1
  
  #
  #- name: Add multiple repositories into the same file (1/2)
  #  yum_repository:
  #    name: rhel-8-for-x86_64-appstream-rpms
  #    description: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
  #    baseurl: https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/appstream/os
  #    enabled: 1
  #    gpgcheck: 1
  #    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  #    sslverify: 1
  #    sslcacert: /etc/rhsm/ca/redhat-uep.pem
  #    sslclientkey: /etc/pki/entitlement/8315695045436431682-key.pem
  #    sslclientcert: /etc/pki/entitlement/8315695045436431682.pem
  #    metadata_expire: 86400
  #    enabled_metadata: 1
  #
  #- name: Add multiple repositories into the same file (2/2)
  #  yum_repository:
  #    name: rhv-4.4-manager-for-rhel-8-x86_64-rpms
  #    description: Red Hat Virtualization Manager 4.4 for RHEL 8 x86_64 (RPMs)
  #    baseurl: https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/rhv-manager/4.4/os
  #    enabled: 1
  #    gpgcheck: 1
  #    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  #    sslverify: 1
  #    sslcacert: /etc/rhsm/ca/redhat-uep.pem
  #    sslclientkey: /etc/pki/entitlement/8315695045436431682-key.pem
  #    sslclientcert: /etc/pki/entitlement/8315695045436431682.pem
  #    metadata_expire: 86400
  #    enabled_metadata: 1
  #
  #- name: fast
  #  yum_repository:
  #    name: fast-datapath-for-rhel-8-x86_64-rpms
  #    description: Fast Datapath for RHEL 8 x86_64 (RPMs)
  #    baseurl: https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/fast-datapath/os
  #    enabled: 1
  #    gpgcheck: 1
  #    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  #    sslverify: 1
  #    sslcacert: /etc/rhsm/ca/redhat-uep.pem
  #    sslclientkey: /etc/pki/entitlement/8315695045436431682-key.pem
  #    sslclientcert: /etc/pki/entitlement/8315695045436431682.pem
  #    metadata_expire: 86400
  #    enabled_metadata: 1
  #
  #- name: jb
  #  yum_repository:
  #    name: jb-eap-7.2-for-rhel-8-x86_64-source-rpms
  #    description: JBoss Enterprise Application Platform 7.2 (RHEL 8) (Source RPMs)
  #    baseurl: https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/jbeap/7.2/source/SRPMS
  #    enabled: 0
  #    gpgcheck: 1
  #    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  #    sslverify: 1
  #    sslcacert: /etc/rhsm/ca/redhat-uep.pem
  #    sslclientkey: /etc/pki/entitlement/8315695045436431682-key.pem
  #    sslclientcert: /etc/pki/entitlement/8315695045436431682.pem
  #    metadata_expire: 86400
  #    enabled_metadata: 0
  #
  ## Handler showing how to clean yum metadata cache
  #- name: yum-clean-metadata
  #  command: yum clean metadata
  #  args:
  #    warn: no
  #
  #- name: Enable postgresql 12
  #  command: dnf module -y enable postgresql:12
  #
  #- name: Enable pki-deps
  #  command: dnf module -y enable pki-deps
  #
  #- name: Distro Sync
  #  command: dnf distro-sync --nobest
  #
  #- name: Install a list of packages 
  #  yum:
  #    name:
  #   - postgresql-contrib
  #   - rhvm 
  #   - ovirt-engine-extension-aaa-ldap-setup
  #    state: present
  #
  #- name: Run engine-setup
  #  command: engine-setup --accept-defaults
