vars

php_module_name: "php"
php_version: "7.4"
php_desired_repo: "remi"
rhv_packages:
  - php-devel
  - php-pdo
  - php-cli
  - php-opcache

tasks

- name: install remi repo
  include_tasks: setup_remi_repo.yml

- name: get the rpm package facts
  package_facts:
    manager: "auto"

- block:
  - name: "Retrieve remote php module file"
    fetch:
      src: "/etc/dnf/modules.d/{{ php_module_name }}.module"
      dest: /tmp/ansible
    changed_when: false  
    
  - name: "Read stream from {{ php_module_name }} module"
    set_fact:
      current_stream: "{{ lookup( 'ini', 'stream section={{ php_module_name }} file=/tmp/ansible/{{ inventory_hostname }}/etc/dnf/modules.d/{{ php_module_name }}.module' ) }}"

  - name: "Remove existing {{ php_module_name }}"
    dnf:
      name: "{{ php_module_name }}"
      state: absent
    when: current_stream != php_desired_stream      
    
  - name: reset {{ php_module_name }} module
    command: "dnf module reset -y {{ php_module_name }}"
    args: 
      warn: false
    when: 
      - current_stream != php_desired_stream
      
  - name: "Enable {{ php_module_name }}:{{ php_desired_stream }} module"
    command: "dnf module enable -y {{ php_module_name }}:{{ php_desired_stream }}"
    args: 
      warn: false
    register: dnf_module_php_enabled
    when: current_stream != php_desired_stream
    
  - name: Install {{ php_module_name }} {{ php_version }} from {{ php_desired_stream }}
    dnf:
      enablerepo: {{ php_desired_repo }}
      name: "@{{ php_module_name }}:{{ php_desired_stream }}"
      state: present
    when: dnf_module_php_enabled

- name: Installing additional PHP packages 
  dnf:
    name: "{{ php_packages }}"
    update_cache: yes
  when: current_stream != php_desired_stream
