---
- hosts: {{ new_vmname }}
  gather_facts: yes
  vars:
    rhsm_repos: 
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms
      - rhv-4.4-manager-for-rhel-8-x86_64-rpms
      - fast-datapath-for-rhel-8-x86_64-rpms
      - jb-eap-7.4-for-rhel-8-x86_64-rpms
      - openstack-16.2-cinderlib-for-rhel-8-x86_64-rpms
      - rhceph-4-tools-for-rhel-8-x86_64-rpms

    paquetes:
      - postgresql-contrib
      - rhvm 
      - ovirt-engine-extension-aaa-ldap-setup
 
    rhsm_pool: 8a85f9997527b04201752908e64d6a5d
    dominio: andreani.com.ar

  tasks:

    - name: Copiar config
      copy: src=rhvm_config.conf dest=/tmp mode=0555

    - name: Reemplazar por el hostname
      replace:
        dest: /tmp/rhvm_config.conf
        regexp: HNAME
        replace: '{{ ansible_hostname }}.{{ dominio }}'
        backup: yes

    - name: Reemplazar por el hostname
      replace:
        dest: /tmp/rhvm_config.conf
        regexp: DOMINIO 
        replace: '{{ dominio }}'
        backup: yes

    - name: Agregar a la tabla de host
      lineinfile:
         path: /etc/hosts
         line: " {{ ansible_ssh_host }} {{ ansible_hostname }}.{{ dominio }} "
         insertbefore: EOF

    - name: "Initializing registration status"
      set_fact:
        registered: false
    
    - name: "Checking subscription status (a failure means it is not registered and will be)"
      command: "/usr/bin/subscription-manager status"
      ignore_errors: yes
      changed_when: no
      register: check_if_registered

    - name: "Set registration fact if system is already registered"
      set_fact:
        registered: true
      when: check_if_registered.rc == 0

    - name: "Cleaning any old subscriptions"
      command: "/usr/bin/subscription-manager clean"
      when:
        - not registered
        - rhsm_authentication is defined
      register: cleaningsubs_result
      until: cleaningsubs_result.rc == 0
      retries: 10
      delay: 1
     
    - name: Register RHEL
      redhat_subscription:      
        state: present
        username: ddf4-90a6-de5f-b290
        password: rhel4ndr34n1#
        pool_ids: "{{ rhsm_pool }}"
        force_register: yes

    - name: "Auto-attach to Subscription Manager Pool"
      command: "/usr/bin/subscription-manager attach --auto"
      when:
        - not registered
        - rhsm_pool is undefined or rhsm_pool is none or rhsm_pool|trim == ''
      register: autoattach_result
      until: autoattach_result.rc == 0
      retries: 10
      delay: 1
    
    #- name: "Attach to a specific pool"
    #  command: "/usr/bin/subscription-manager attach --pool={{ rhsm_pool }}"
    #  when:
    #    - rhsm_pool is defined
    #    - rhsm_pool is not none
    #    - rhsm_pool|trim != ''
    #    - not registered
    #  register: attachpool_result
    #  until: attachpool_result.rc == 0
    #  retries: 10
    #  delay: 1
        
    - name: "Disable all repositories"
      command: "/usr/bin/subscription-manager repos --disable=*"
      when:
#        - not registered
        - rhsm_repos is defined
        - rhsm_repos is not none
        - rhsm_repos|trim != ''

    - name: "Enable specified repositories"
      command: "/usr/bin/subscription-manager repos --enable={{ item }}"
      with_items: "{{ rhsm_repos }}"
      when:
#        - not registered
        - rhsm_repos is defined
        - rhsm_repos is not none
        - rhsm_repos|trim != ''
      register: enablerepos_result
      until: enablerepos_result.rc == 0
      retries: 10
      delay: 1
  
  ## Handler showing how to clean yum metadata cache
    - name: yum-clean-metadata
      command: "/usr/bin/yum clean metadata"
      args:
        warn: no
  #   
    - name: Enable postgresql 12
      command: "/usr/bin/dnf module -y enable postgresql:12"
      register: enable_postgresql

   
    - name: Enable pki-deps
      command: "/usr/bin/dnf module -y enable pki-deps"
      register: enable_pki_deps
   
#    - name: Distro Sync
#      command: "dnf distro-sync --nobest"
#      register: distro_sync_nobest
   
#    - name: Install a list of packages 
#      yum:
#        name:
#          - postgresql-contrib
#          - rhvm 
#          - ovirt-engine-extension-aaa-ldap-setup
#        state: present

    - name: Install a list of packages 
      yum:
        name: "{{ paquetes }}"
        state: present
        update_cache: no
  #  
    - name: Run engine-setup
      command: "engine-setup --config=/tmp/rhvm_config.conf"
      register: engine_setup
      async: 900
      poll: 10
