---
- name: Get tag from virtual machine
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Gather detailed information about tags and category associated with the given VM
    vmware_guest_info:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      datacenter: "DCGLA"
      name: "INFNTB01"
      tags: True
      tag_details: True
    register: detailed_tag_info

  - name: save the Json data to a Variable as a Fact
    set_fact:
      #jsondata: "{{ detailed_tag_info | from_json  }}"
      jsondata: "{{ detailed_tag_info | to_json  }}"

  - name: set gerencia
    set_fact:
      tags_gerencia: "{{ jsondata | json_query(jmesquery) }}"
    vars:
      jmesquery: 'instance.tags.category_name'

  - debug:
      #msg: "Categorias {{ jsondata }}"
      msg: "Categorias {{ tags_gerencia }}"
