---
- hosts: all
  gather_facts: True

  tasks:
  - name: Install RHSM and Insights
    yum:
      name: '{{ item }}'
      state: present
    with_items:
    - redhat-access-insights
    - subscription-manager
    
  - name: Register system
    redhat_subscription:
      state: present
      username: '{{ rhsm_username }}'
      password: '{{ rhsm_password }}'
      pool_ids: '{{ rhsm_pool }}'
    when: ansible_facts['os_family'] == "RedHat"
  

