- name: Registrar RHELS
  hosts: all
  gather_facts: true
 
  tasks:   
  - name: Register
    redhat_subscription:
      state: present
      username: '{{ lookup("env", "RHEL_username") }}'
      password: '{{ lookup("env", "RHEL_password") }}'
      pool_ids: '{{ lookup("env", "RHEL_pool") }}'
    when: ansible_facts['os_family'] == "RedHat"
  
  - name: debug
    debug:
      msg: "{{ lookup("env", "RHEL_username") }} {{ lookup("env", "RHEL_password") }} {{ lookup("env", "RHEL_pool") }}"
