- name: Check if this Red Hat is subscribed to something
  hosts: all
  gather_facts: true
  
  tasks:
  - name: Check registration command
    shell: subscription-manager list
    register: command_result
    failed_when: command_result.rc != 0 or 'Subscribed' not in command_result.stdout
    changed_when: false
    when: ansible_facts['os_family'] == "RedHat"
    
  - name: Resultados
    debug:
      msg: "{{command_result.stdout.split('\n')}}"
    when: ansible_facts['os_family'] == "RedHat"
   
