# refference https://docs.pagure.org/sssd.sssd/design_pages/active_directory_access_control.html
- name: "Add {{ adgroup }} group for ssh access on sssd"
  hosts: all
  gather_facts: true
  vars:
  - sssdconf: /etc/sssd/sssd.conf
  
  tasks:
  - name: Check join status
    shell: realm list
    register: command_result
    failed_when: command_result.rc != 0 or "ANDREANI.COM.AR" not in command_result.stdout
    
  - name: "sudo without password for superusuarios group"
    blockinfile:
      dest: "{{ sssdconf }}"
      insertafter: [domain/andreani.com.ar]
      block: |
        ad_access_filter = (memberOf=CN=superusuarios,OU=Grupos Andreani,DC=andreani,DC=com,DC=ar)
      
  - name: "sudo without password for {{ adgroup }} group"
    blockinfile:
      dest: "{{ sssdconf }}"
      block: |
        ad_access_filter = (&(memberOf=CN=superusuarios,OU=Grupos Andreani,DC=andreani,DC=com,DC=ar)(memberOf={{ adgroup}}))
        
  - name: sshd restart
    service:
      name: sssd
      state: restarted
      enabled: true
        
  
