- name: Registrar RHELS
  hosts: all
  gather_facts: true
 
  tasks:   
  - name: debug
    debug:
      msg: '{{ lookup("env", "rhsm_username") }} {{ lookup("env", "rhsm_password") }} {{ lookup("env", "rhsm_pool") }}'
      
  - name: Register
    redhat_subscription:
      state: present
      username: '{{ lookup("env", "rhsm_username") }}'
      password: '{{ lookup("env", "rhsm_password") }}'
      pool_ids: '{{ lookup("env", "rhsm_pool") }}'
    when: ansible_facts['os_family'] == "RedHat"
  

