- name: Check if this Red Hat is subscribed to something
  hosts: all
  gather_facts: true
  
  tasks:
  - name: "check if package is installed on Red Hat family"
    shell: rpm -q insights-client
    changed_when: false
    register: package_check
    when: ansible_facts['os_family'] == "RedHat"
    
  - name: Check registration command
    shell: insight-client --status
    register: command_result
    failed_when: command_result.rc != 0 or 'Insights API confirms registration.' not in command_result.stdout
    changed_when: false
    when: ansible_facts['os_family'] == "RedHat"
    
  - name: Resultados
    debug:
      msg: "{{command_result.stdout.split('\n')}}"
    when: ansible_facts['os_family'] == "RedHat"
