- name: Check if this Red Hat is subscribed to something
  hosts: all
  gather_facts: true
  
  tasks:
  - name: "check if package is installed on Red Hat family"
    yum:
      name: insights-client
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Check registration command
    shell: insights-client --status
    register: status_result
    #changed_when: false
    ignore_errors: yes
    when: ansible_facts['os_family'] == "RedHat"
    
  - name: Check registration command
    shell: insights-client --register --display-name=${HOSTNAME} --force-reregister
    register: command_result
    failed_when: command_result.rc != 0
    changed_when: false
    when: status_result.rc != 0 or 'Insights API confirms registration.' not in status_result.stdout
    
#  - name: Resultados
#    debug:
#      msg: "{{command_result.stdout.split('\n')}}"
#    when: ansible_facts['os_family'] == "RedHat"
      
  - name: Resultados
    debug:
      msg: "{{item.stdout.split('\n')}}"
    loop: "{{ command_result }}"
    when: ansible_facts['os_family'] == "RedHat"  
    
