
- name: Get info about tag
  vmware_tag_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
  delegate_to: localhost

- name: Get category id from the given tag
  vmware_tag_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
  delegate_to: localhost
  register: tag_details
- debug:
    msg: "{{ tag_details.tag_facts['fedora_machines']['tag_category_id'] }}"

#
#- name: Write tags for RedHat Insight
#  hosts: all
#  strategy: free
#  gather_facts: yes
#  become: true
#  vars: 
#    log4jdir: /tmp/log4j
#    filelog: "{{log4jdir}}/log4j-detect-{{ansible_hostname}}-status.log"
#
#  tasks:
#  - name: "Check directory"
#    stat:
#      path: "{{log4jdir}}"
#    register: l4j

#  - name: "Delete content & directory"
#    file:
#      state: absent
#      path: "{{log4jdir}}"
#    when: l4j.stat.exists == true
#
#  - name: "Create directory"
#    file:
#      path: "{{log4jdir}}"
#      state: directory
#      mode: 0755
#      group: root
#      owner: root
#
#  - name: "Transfer check script"
#    copy:
#      src: "log4j_status.sh"
#      dest: "{{log4jdir}}"
#      mode: '0755'
#     
#  - name: "Transfer check script"
#    copy:
#      src: "log4j-detect"
#      dest: "{{log4jdir}}"
#      mode: '0755'
#
#  - name: Execute a validate shell script
#    shell: "{{log4jdir}}/log4j_status.sh {{log4jdir}} {{ansible_hostname}}"
#    args:
#      chdir: "{{log4jdir}}"
#    register: command_result
#    failed_when: command_result.rc != 0
#    changed_when: False
#
#  - name: check files affected
#    shell: grep "No vulnerabilities were detected" "{{ filelog }}"
#    changed_when: false
