# refference https://docs.pagure.org/sssd.sssd/design_pages/active_directory_access_control.html
- name: "Add {{ adgroup }} group for ssh access on sssd"
  hosts: all
  gather_facts: true
  vars:
    joineado: 'realm-name\: ANDREANI.COM.AR'
  
  tasks:
  - name: Check join status
    shell: realm list
    register: command_result
    failed_when: command_result.rc != 0 or {{ joineado }} not in command_result.stdout
    
  - name: "sudo without password for superusuarios group"
    blockinfile:
      dest: /tmp/test.txt
      insertafter: [domain/andreani.com.ar]
      block: |
        ad_access_filter = (memberOf=CN=superusuarios,OU=Grupos Andreani,DC=andreani,DC=com,DC=ar)
      
  - name: "sudo without password for {{ adgroup }} group"
    blockinfile:
      dest: /tmp/test.txt
      block: |
        ad_access_filter = (&(memberOf=CN=superusuarios,OU=Grupos Andreani,DC=andreani,DC=com,DC=ar)(memberOf={{ adgroup}}))
