- name: Copy status script , execute it and transfer file to admit.
  hosts: all
  strategy: free
  gather_facts: yes
  become: true

  tasks:
  - name: "Transfer check script"
    copy:
      src: "log4j_status.sh"
      dest: /tmp/log4j_status.sh
      mode: '0755'
     
  - name: "Transfer check script"
    copy:
      src: "log4j-detect"
      dest: /tmp/log4j-detect
      mode: '0755'

  - name: Execute a validate shell script
    shell: "/tmp/log4j_status.sh {{ansible_hostname}}"
    args:
      chdir: /tmp/
    register: command_result
    failed_when: command_result.rc != 0
    changed_when: False

  - name: use find to get the files list which you want to copy/fetch
    find: 
      paths: /tmp/
      patterns: "log4j-detect-.*-status.log$"
      use_regex: True   
    register: status_fetch
    
  - name: use fetch to get the files
    fetch:
      src: "{{ item.path }}"
      dest: /tmp/log4j/
      flat: yes
    with_items: "{{ status_fetch.files }}"
