---
- hosts: all
  strategy: free
  gather_facts: no
  become: true
  var:
    logfile: "/tmp/log4j-detect-{{ansible_hostname}}.log"

  tasks:
  - name: "Transfer check script"
    copy:
      src: "log4j-detect"
      dest: /tmp/
      mode: '0755'

  - name: Execute log4j-detect
Pzgre
    shell: /tmp/log4j-detect > "{{logfile}}"
    args:
      creates log4j-detect.log
    register: log4j-detect.result
#    failed_when: command_result.rc != 0 or command_result.rc 
    changed_when: False 

  - name: check if vulnerable files are found
    lineinfile: 
      dest: "{{logfile}}"
      line: "Vulnerable Files"
    check_mode: yes
    register: status_fetch
    failed_when: presence.changed

  - name: use fetch to get the files
    fetch:
      src: "{{ item.path }}"
      dest: /tmp/log4j/
      flat: yes
    with_items: "{{ status_fetch.files }}"
