- collections:
  - fortinet.fortios
  connection: httpapi
  hosts: all
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    vdom: root
  tasks:
  - name: fortios_firewall_internet_service
    fortios_firewall_internet_service:
      username: pvera
      password: andreani2021
      vdom: root
      state: present
      firewall_internet_service:
        database: isdb
        direction: dst
        extra_ip_range_number: 0
        icon_id: 114
        id: 7471105
        ip_number: 0
        ip_range_number: 0
        name: Okta-Web
        obsolete: 0
        reputation: 0
        singularity: 0
        sld_id: 0
