---
- name: Add tags to a virtual machine
  community.vmware.vmware_tag_manager:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    tag_names:
      - '{{ t1 }}'
      - '{{ t2 }}'
      - '{{ t3 }}'
      - '{{ t4 }}'
    object_type: VirtualMachine
    state: add
  delegate_to: localhost
