---
- name: VMwareVM-fromTemplate
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: "vcenter-gla.andreani.com.ar"
      username: "{{ vcsa_username }}"
      password: "{{ pwd }}"
      validate_certs: no
      name: "{{ new_vmname }}"
      template: "rhel8-podman-final-desa-template"
      datacenter: "DCGLA-DESA-TEST"
      folder: "/Infra Linux - DESA"
      cluster: "CL-GLA-DESA-TEST"
      state: poweredon
      wait_for_ip_address: no
      disk:
      - size_gb: "{{ host_disk_size }}"
        type: "eagerzeroedthick"
        datastore: "SC-Datastore-05"
      hardware:
        memory_mb: "{{ host_memory }}"
        num_cpus: "{{ host_cpus }}"
#        num_cpu_cores_per_socket: "1"
#        scsi: paravirtual
#        memory_reservation_lock: False
#        mem_reservation: 0
#        hotadd_cpu: False
#        hotremove_cpu: False
#        hotadd_memory: True
#        version: 18 # Hardware version of virtual machine
    delegate_to: localhost
    register: deploy
