---
- name: VMwareVM-fromTemplate
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: no
      name: "{{ new_vmname }}"
      template: "nu-template-podman"
      datacenter: "DCGLA-DESA-TEST"
      folder: "/Linux-test"
      cluster: "CL-GLA-DESA-TEST"
      state: poweredon
      wait_for_ip_address: no
      disk:
      - size_gb: "{{ vm_disk_size }}"
        type: "eagerzeroedthick"
        datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: "{{ vm_memory *1024|int }}"
        num_cpus: "{{ vm_cpus }}"
        scsi: paravirtual
        hotadd_memory: True
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gateway }}"
        dns_servers:
        - 10.20.2.115
        - 10.20.2.116
        start_connected: True
      customization:
        dns_suffix: andreani.com.ar
        dns_servers:
        - 10.20.2.115
        - 10.20.2.116
    delegate_to: localhost
    register: deploy

  - name: Sleep for 300 seconds to initialize vmware tools
    wait_for:
      timeout: 300
    delegate_to: localhost

