- name: Add tags to a virtual machine
  host: localhost
  connection: local
  tasks:
  - name: tag
    community.vmware.vmware_tag_manager:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: no
      tag_names:
        - os:linux
      object_name: rhvmprueba
      object_type: VirtualMachine
      state: add
    delegate_to: localhost

#---
#- name: Add tags to a virtual machine
#  hosts: localhost
#  connection: local
#  gather_facts: no
#  tasks:
#  - name: Tag vms
#    vmware_tag_manager:
#      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
#      username: '{{ lookup("env", "VMWARE_USER") }}'
#      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
#      validate_certs: no
#      tag_names:
#        - os: "{{ os_type | default('not-defined') }}"
#        - hardware: "{{ hardware_type | default('not-defined') }}"
#        - ubicacion: " {{ ubicacion | default('not-defined') }}"
#        - pservicio: " {{ pservicio | default('not-defined') }}"
#        - versionso: " {{ versionso | default('not-defined') }}"
#        - severidad: " {{ severidad | default('not-defined') }}"
#        - ambiente: "{{ ambiente | default('not-defined') }}"
#      object_name: "{{ new_vmname }}"
#      object_type: VirtualMachine
#      state: add
#    delegate_to: localhost
