---
- name: VMwareVM-fromTemplate
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: "vcenter-gla.andreani.com.ar"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password}}"
      validate_certs: no
      name: "{{ new_vmname }}"
      template: "rhel8-podman-final-desa-template"
      datacenter: "DCGLA-DESA-TEST"
      folder: "/Infra Linux - DESA"
      cluster: "CL-GLA-DESA-TEST"
      state: poweredon
      wait_for_ip_address: no
      disk:
      - size_gb: "{{ vm_disk_size }}"
        type: "eagerzeroedthick"
        datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: "{{ host_memory *1024|int }}"
        num_cpus: "{{ host_cpus }}"
#        num_cpu_cores_per_socket: "1"
        scsi: paravirtual
#        memory_reservation_lock: False
#        mem_reservation: 0
#        hotadd_cpu: False
#        hotremove_cpu: False
        hotadd_memory: True
#        version: 18 # Hardware version of virtual machine
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gateway }}"
      
    delegate_to: localhost
    register: deploy
